// Coloque aqui suas actions
export const getUser = 'GET_USER';
export const validEmail = 'VALID_EMAIL';
export const fetchAPISUCESS = 'FETCH_API_SUCESS';
export const fetchAPIERROR = 'FETCH_API_ERROR';
export const fetchAPI = 'fetchAPI';
export const SET_TIMER = 'SET_TIMER';
export const SET_POINT = 'SET_POINT';
export const RESET = 'RESET';
